name: Cypress Performance Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  performance_tests:
    strategy:
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install

      - name: Grant execute permissions to Cypress
        run: chmod +x ./node_modules/.bin/cypress

      - name: Run Cypress tests - Instance ${{ matrix.instance }}
        run: npx cypress run --spec "cypress/e2e/venta-unlimit-sencillo.cy.js" --group "instance-${{ matrix.instance }}"

      # Opcional: Recopilar y reportar resultados
      # ...
